//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMVCUI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personel
    {
        public int Id { get; set; }

        [Display(Name = "Departman Adý")]
        [Required(ErrorMessage = "Lütfen bir departman seçiniz.")]
        public Nullable<int> DepartmanId { get; set; }

        [Required(ErrorMessage = "Ad alaný zorunludur.")]
        public string Ad { get; set; }

        [Required(ErrorMessage = "Ad alaný zorunludur.")]
        public string Soyad { get; set; }

        [Display(Name = "Maaþ")]
        [Required(ErrorMessage = "Maaþ alaný zorunludur.")]
        [Range(2324,8000,ErrorMessage =  "Maaþ alaný 2324 ile 8000 arasýnda olmalýdýr.")]
        public Nullable<short> Maas { get; set; }

        [Display(Name = "Doðum Tarihi")]
        [Required(ErrorMessage = "Lütfen doðum tarihini seçiniz.")]
        public Nullable<System.DateTime> DogumTarihi { get; set; }

        [Required(ErrorMessage = "Lütfen cinsiyetinizi belirtiniz.")]
        public bool Cinsiyet { get; set; }

        [Display(Name = "Evlilik Durumu")]
        public bool EvliMi { get; set; }
    
        public virtual Departman Departman { get; set; }
    }
}
